# Site settings

# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM


# Permalinks
permalink:        pretty
relative_permalinks: true


# Setup
title:            "DioT Labs and Guides"
tagline:          'CMU Mini 3 - Spring 2016'

email: 			daragh@daraghbyrne.me

description:     "A series of guides, tutorials and labs to accompany CMU's <a href='http://daraghbyrne.github.io/diot2016/'>DIoT Spring 2016 course</a>; a hands-on introductory course exploring the Internet of Things and connected product experiences."
-- url:              http://diotlabs.daraghbyrne.me
baseurl:          /diotlabs

author:
  name:           'Daragh Byrne'
  email: 		  daragh@daraghbyrne.me
  url:            http://daraghbyrne.github.io/diotlabs/

email: 			  daragh@daraghbyrne.me
twitter_username: diotlabs
github_username:  daraghbyrne

paginate:         5

# Custom vars
version:          1.0.0

github:
  user:           daraghbyrne
  repo:           https://github.com/daraghbyrne/diotlabs
  
  
  
# The left menu bar
menu:
    items:
      - text: "Introduction"
        relativeUrl: /
      - text: "Getting Started"
        relativeUrl: /getting-started/
        items:
          - text: "What is the Particle Platform"
            relativeUrl: /getting-started/the-particle-platform
          - text: "Understanding your Photon"
            relativeUrl: /getting-started/understanding-your-photon
          - text: "Setting up your Photon"
            relativeUrl: /getting-started/setting-up-your-photon
          - text: "The Particle Community"
            relativeUrl: /getting-started/the-particle-community

      - text: "1. A Simple Internet Appliance"
        relativeUrl: /1-a-simple-internet-appliance/
        items:
          - text: "Learn: Understanding Breadboards"
            relativeUrl: /1-a-simple-internet-appliance/breadboards
          - text: "Learn: Understanding Jumper Wires"
            relativeUrl: /1-a-simple-internet-appliance/jumpers
          - text: "Learn: Understanding Resistors"
            relativeUrl: /1-a-simple-internet-appliance/resistors
          - text: "Learn: Understanding LEDs"
            relativeUrl: /1-a-simple-internet-appliance/leds
      - text: "Tips and Troubleshooting"
        relativeUrl: /tips-and-troubleshooting/
      - text: "Resources"
        relativeUrl: /resources/
      - text: "FAQ"
        relativeUrl: /faq/
      - text: "DIoT 2016"
        absoluteUrl: http://daraghbyrne.github.io/diot2016
